apiVersion: opencontext.com/v1alpha1
kind: Scheme
metadata:
  namespace: scatter-ly
  name: blue-sky
  description: Everything related to the raccoon Blue Sky Buffet project
  links:
    - url: https://buffet.example.com
      title: Project diagrams
    - url: http://example.com/schemes/orchard/dashboard
      title: Buffet Metrics Dashboard
      icon: dashboard
spec:
  owner: [scatter-ly/team-raccoon]
---
apiVersion: opencontext.com/v1alpha1
kind: Platform
metadata:
  namespace: scatter-ly
  name: retail
  description: User experience platform
spec:
  owner: [scatter-ly/eng-raccoon-eco, scatter-ly/prod-raccoon]
  scheme: scatter-ly/blue-sky
---
apiVersion: opencontext.com/v1alpha1
kind: Scheme
metadata:
  namespace: scatter-ly
  name: orchard
  description: Everything related to the squirrel orchard project
  links:
    - url: https://orchard.example.com
      title: Orchard here
    - url: http://example.com/schemes/orchard/dashboard
      title: Orchard Metrics Dashboard
      icon: dashboard
spec:
  owner: [scatter-ly/team-squirrel]
---
apiVersion: opencontext.com/v1alpha1
kind: Platform
metadata:
  namespace: scatter-ly
  name: crates
  description: Shipping & receiving platform
spec:
  owner: [scatter-ly/eng-squirrel, scatter-ly/prod-squirrel]
  scheme: scatter-ly/orchard
---
apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  namespace: scatter-ly
  name: eng-raccoon-info
  title: Eng Raccoon Info
  description: Additional links for Eng Raccoon
  links:
    - url: https://slack.com
      title: Slack
      icon: chat
    - url: https://jira.com
      title: Jira
      icon: dashboard
spec:
  type: infocard
  lifecycle: production
  owner: [scatter-ly/eng-raccoon]
---
apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  namespace: scatter-ly
  name: eng-raccoon-cloud-info
  title: Eng Raccoon Cloud Info
  description: Additional links for Eng Raccoon Cloud
  links:
    - url: https://slack.com
      title: Slack
      icon: chat
    - url: https://jira.com
      title: Jira
      icon: dashboard
spec:
  type: infocard
  lifecycle: production
  owner: [scatter-ly/eng-raccoon-cloud]
---
apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  namespace: scatter-ly
  name: eng-squirrel-info
  title: Engineering Squirrel Info
  description: Additional links for Engineering Squirrel
  links:
    - url: https://slack.com
      title: Slack
      icon: chat
    - url: https://jira.com
      title: Jira
      icon: dashboard
spec:
  type: infocard
  lifecycle: production
  owner: [scatter-ly/eng-squirrel]
---
apiVersion: opencontext.com/v1alpha1
kind: Team
metadata:
  namespace: scatter-ly
  name: engineering
  description: Engineering Team
spec:
  type: virt-org
  profile:
    displayName: Engineering Team
    email: engineering@example.com
    picture: https://avatars.dicebear.com/api/identicon/engineering@example.com.svg?background=%23fff&margin=2
  children:
    [scatter-ly/eng-squirrel, scatter-ly/eng-raccoon, scatter-ly/reviewers, scatter-ly/docs-core, scatter-ly/dev-core, scatter-ly/maintainers]
---
apiVersion: opencontext.com/v1alpha1
kind: Team
metadata:
  namespace: scatter-ly
  name: product
  description: Product team
spec:
  type: virt-org
  profile:
    displayName: Product Team
    email: product@example.com
    picture: https://avatars.dicebear.com/api/identicon/product@example.com.svg?background=%23fff&margin=2
  children: [scatter-ly/prod-squirrel, scatter-ly/prod-raccoon]
---
apiVersion: opencontext.com/v1alpha1
kind: Team
metadata:
  namespace: scatter-ly
  name: team-squirrel
  description: Squirrel Team
  links:
    - url: https://example.com/squirrel-team-handbook
      title: Team Handbook
spec:
  type: department
  profile:
    displayName: Team Squirrel
    email: team-squirrel@scatterly.com
    picture: https://avatars.dicebear.com/api/identicon/team-squirrel@example.com.svg?background=%23fff&margin=2
    timezone: America/New_York
    slackHandle: squirrel_team
    pagerHandle: squirrel_team
  children: [scatter-ly/eng-squirrel, scatter-ly/prod-squirrel]
  members: [scatter-ly/alchen99, scatter-ly/bdwalter, scatter-ly/jwithington]
---
apiVersion: opencontext.com/v1alpha1
kind: Team
metadata:
  namespace: scatter-ly
  name: team-raccoon
  description: Raccoon Team
  links:
    - url: https://example.com/raccoon-team-handbook
      title: Team Handbook
spec:
  type: department
  profile:
    displayName: Team Raccoon
    email: team-raccoon@scatterly.com
    picture: https://avatars.dicebear.com/api/identicon/catalog-eng@example.com.svg?background=%23fff&margin=25
    timezone: America/Los_Angeles
    slackHandle: raccoon_team
    pagerHandle: raccoon_team
  children: [scatter-ly/eng-raccoon, scatter-ly/prod-raccoon]
  members: [scatter-ly/aeschright, scatter-ly/bcornils, scatter-ly/chris-schnaidt]

